# Generated by Django 4.2.15 on 2024-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image_list', models.TextField(blank=True, null=True)),
                ('key_features_list', models.TextField(blank=True, null=True)),
                ('features_list', models.TextField(blank=True, null=True)),
                ('specifications_list', models.TextField(blank=True, null=True)),
                ('documents_list', models.TextField(blank=True, null=True)),
                ('product_link', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
    ]
