# Generated by Django 4.2.15 on 2024-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage_absolute', models.CharField(blank=True, max_length=100, null=True)),
                ('regular_price_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_main', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('ean13', models.CharField(blank=True, max_length=100, null=True)),
                ('upc', models.CharField(blank=True, max_length=100, null=True)),
                ('product_variation', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.CharField(blank=True, max_length=300, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('animal', models.CharField(blank=True, max_length=500, null=True)),
                ('idade', models.CharField(blank=True, max_length=200, null=True)),
                ('porte', models.CharField(blank=True, max_length=200, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=200, null=True)),
                ('alimento', models.CharField(blank=True, max_length=200, null=True)),
                ('gama', models.CharField(blank=True, max_length=200, null=True)),
                ('proteina_sabor', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_produto', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('image_links', models.TextField(blank=True, null=True)),
                ('name_variants', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
    ]
