# Generated by Django 4.2.15 on 2024-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
