# Generated by Django 4.2.15 on 2024-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_product_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
