# Generated by Django 4.2.15 on 2024-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_link', models.CharField(blank=True, max_length=255, null=True)),
                ('link_sale', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
