# Generated by Django 4.2.15 on 2024-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('link_description', models.CharField(blank=True, max_length=500, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.CharField(blank=True, max_length=500, null=True)),
                ('page_categories', models.CharField(blank=True, max_length=500, null=True)),
                ('video_sd_url', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('total_active_time', models.CharField(blank=True, max_length=100, null=True)),
                ('collation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_archive_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
