# Generated by Django 4.2.15 on 2024-11-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='total_active_time',
        ),
    ]
