# Generated by Django 4.2.15 on 2024-11-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_ads_total_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
