# Generated by Django 4.2.15 on 2024-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_ads_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='video_sd_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
