# Generated by Django 4.2.15 on 2024-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='operating_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
