# Generated by Django 4.2.15 on 2024-12-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_agent_operating_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='rera_number',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='website',
        ),
    ]
