# Generated by Django 4.2.15 on 2024-10-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_ads', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
    ]
