# Generated by Django 4.2.15 on 2024-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=500, null=True)),
                ('account_id', models.CharField(blank=True, max_length=500, null=True)),
                ('license_number', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_primary', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('website_url', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('street_number', models.CharField(blank=True, max_length=500, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
    ]
