# Generated by Django 4.2.15 on 2024-10-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAds1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_ads', models.CharField(max_length=500)),
                ('status', models.CharField(default='New', max_length=10)),
            ],
        ),
    ]
